// Generated by CoffeeScript 1.9.1
(function() {
  var BNP;

  BNP = require('coffeenode-bitsnpieces');


  /*
  active characters:
  \`*_^[]!&<>{}$%@~+=:
   */

  this.get = function(settings) {
    var ref, ref1, rule;
    rule = {};
    rule._matcher = (ref = settings != null ? settings['matcher'] : void 0) != null ? ref : '!!';
    rule._chr_count = rule._matcher.length;
    rule.terminators = rule._matcher[0];
    rule._class_name = (ref1 = settings != null ? settings['name'] : void 0) != null ? ref1 : 'newline';
    rule.name = 'REMARKABLY/examples/' + rule._class_name;
    rule.about = "$name$ recognizes a given markup and turns it into an HTML `<br>` tag.";
    rule.parse = function(state, silent) {
      var pos, src;
      src = state.src, pos = state.pos;
      if (src.slice(pos, pos + rule._chr_count) !== rule._matcher) {
        return false;
      }
      if (!silent) {
        state.push({
          type: rule.name,
          matcher: rule._matcher,
          block: false,
          level: state.level
        });
      }
      state.pos += rule._chr_count;
      return true;
    };
    rule.render = function(tokens, idx) {
      return "<br>";
    };
    rule.extend = function(self) {
      self.inline.ruler.before(self.inline.ruler['__rules__'][0]['name'], rule.name, rule.parse);
      self.renderer.rules[rule.name] = rule.render;
      return null;
    };
    return rule;
  };

}).call(this);
