// Generated by CoffeeScript 1.8.0
(function() {
  var TEXT, TRM, TYPES, alert, badge, debug, echo, glob, help, info, log, njs_path, rpr, urge, warn, whisper;

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'REMARKABLY';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  TEXT = require('coffeenode-text');

  TYPES = require('coffeenode-types');

  glob = require('glob');

  this.ReMarkable = require('remarkable-dev');

  this._terminator_chrs = (require('remarkable-dev/lib/rules_inline/text'))['terminatorChrs'];

  this._discover = function() {
    var R, collection_name, extension_name, globber, route, _i, _len, _ref;
    globber = njs_path.join(__dirname, './*/*.js');
    R = [];
    _ref = glob.sync(globber);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      route = _ref[_i];
      extension_name = ((njs_path.basename(route)).replace(/\.js$/, '')).replace(/-/g, '_');
      collection_name = (njs_path.basename(njs_path.dirname(route))).replace(/-/g, '_');
      R.push([collection_name, extension_name, route]);
    }
    return R;
  };

  this._extend = function(collection_name, extension_name, route) {
    var getter, target, _base;
    getter = (function(_this) {
      return function(settings) {
        var R, about, chr, chrs, extension, method, method_name, name, terminators, _i, _j, _len, _len1, _ref;
        extension = require(route);
        R = extension.get != null ? extension.get(settings) : extension;
        name = R['name'] != null ? R['name'] : R['name'] = "REMARKABLY/" + collection_name + "/" + extension_name;
        about = R['about'] != null ? R['about'] : R['about'] = "(no documentation for $name$)";
        R['about'] = about.replace(/\$name\$/g, name);
        if ((terminators = R.terminators) != null) {
          chrs = TYPES.isa_list(terminators) ? terminators : TEXT.split(terminators);
          for (_i = 0, _len = chrs.length; _i < _len; _i++) {
            chr = chrs[_i];
            _this._terminator_chrs[chr] = true;
          }
        }
        _ref = ['parse', 'render', 'extend'];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          method_name = _ref[_j];
          if ((method = R[method_name]) != null) {
            R[method_name] = method.bind(R);
          }
        }
        return R;
      };
    })(this);
    target = (_base = this.get)[collection_name] != null ? _base[collection_name] : _base[collection_name] = {};
    target[extension_name] = getter;
    return null;
  };

  this.get = {};

  (function(_this) {
    return (function() {
      var collection_name, extension_name, route, _i, _len, _ref, _ref1, _results;
      _ref = _this._discover();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], collection_name = _ref1[0], extension_name = _ref1[1], route = _ref1[2];
        _results.push(_this._extend(collection_name, extension_name, route));
      }
      return _results;
    });
  })(this)();

  this.use = function(remarkable_parser, extension) {
    return remarkable_parser.use(extension.extend);
  };

  this.main = function() {
    var RM, RMY, angles, braces, brackets, emphasis, emphasis2, enable, html, settings, smh, source, video;
    RMY = this;
    enable = 'full';
    settings = {
      html: true,
      xhtmlOut: false,
      breaks: false,
      langPrefix: 'language-',
      linkify: true,
      typographer: true,
      quotes: '“”‘’'
    };
    RM = new RMY.ReMarkable(enable, settings);
    RMY.use(RM, video = RMY.get.examples.video());
    RMY.use(RM, emphasis = RMY.get.examples.emphasis());
    RMY.use(RM, emphasis2 = RMY.get.examples.emphasis2());
    RMY.use(RM, braces = RMY.get.examples.brackets({
      opener: '{',
      closer: '}',
      arity: 2,
      name: 'braces'
    }));
    RMY.use(RM, angles = RMY.get.examples.brackets({
      opener: '<',
      closer: '>',
      arity: 2,
      name: 'angles'
    }));
    RMY.use(RM, brackets = RMY.get.examples.brackets({
      opener: '[',
      closer: ']',
      arity: 3,
      name: 'brackets-3'
    }));
    RMY.use(RM, smh = RMY.get.examples.brackets({
      opener: '《',
      closer: '》',
      arity: 1,
      name: 'book-title'
    }));
    source = "=This= ==is== ===very=== _awesome_(c): %[example movie](http://example.com)\n*A* **B** ***C*** ****D****\n\nHere are\n* <<double pointy brackets>>,\n* {{double braces}},\n* [[[triple square brackets]]],\n* 也可以用 《中文書名号》 。".trim();
    whisper(source);
    return info(html = RM.render(source));
  };

  if (module.parent == null) {
    this.main();
  }

}).call(this);
